import * as esbuild from 'esbuild';
import * as fs from 'fs';

const isWatch = process.argv.includes('--watch');

async function build() {
  // TypeScript 빌드
  await esbuild.build({
    entryPoints: ['src/Code.ts'],
    bundle: true,
    outfile: 'dist/temp.js',
    platform: 'neutral',
    target: 'es2020',
    format: 'cjs',
    logLevel: 'info',
    sourcemap: false,
    minify: false
  });

  // 빌드된 파일 읽기
  const tempCode = fs.readFileSync('dist/temp.js', 'utf-8');

  // Apps Script 호환 코드로 래핑
  const wrappedCode = `// Apps Script Project
// Generated: ${new Date().toISOString()}
// DO NOT EDIT THIS FILE DIRECTLY - Edit src/Code.ts instead

(function() {
${tempCode}

// Export all functions to global scope
var exports = module.exports;
for (var key in exports) {
  if (exports.hasOwnProperty(key)) {
    this[key] = exports[key];
  }
}
}).call(this);
`;

  // 최종 파일 작성
  fs.writeFileSync('dist/Code.js', wrappedCode);

  // 임시 파일 삭제
  fs.unlinkSync('dist/temp.js');

  console.log('✅ Build complete');
}

async function watch() {
  console.log('👀 Watching for changes...');

  const ctx = await esbuild.context({
    entryPoints: ['src/Code.ts'],
    bundle: true,
    outfile: 'dist/temp.js',
    platform: 'neutral',
    target: 'es2020',
    format: 'cjs',
    logLevel: 'info',
    sourcemap: false,
    minify: false,
    plugins: [{
      name: 'watch-plugin',
      setup(build) {
        build.onEnd(async () => {
          const tempCode = fs.readFileSync('dist/temp.js', 'utf-8');
          const wrappedCode = `// Apps Script Project
// Generated: ${new Date().toISOString()}
// DO NOT EDIT THIS FILE DIRECTLY - Edit src/Code.ts instead

(function() {
${tempCode}

// Export all functions to global scope
var exports = module.exports;
for (var key in exports) {
  if (exports.hasOwnProperty(key)) {
    this[key] = exports[key];
  }
}
}).call(this);
`;
          fs.writeFileSync('dist/Code.js', wrappedCode);
          fs.unlinkSync('dist/temp.js');
          console.log('✅ Rebuilt');
        });
      }
    }]
  });

  await ctx.watch();
}

if (isWatch) {
  await watch();
} else {
  await build();
}
